// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVlOZnTx0dX8xidMaqk6CHH1Ly6ySRhtQ',
    appId: '1:198214518669:web:46acd59cae85f10ae59fc4',
    messagingSenderId: '198214518669',
    projectId: 'daftarbelanja-fb1b4',
    authDomain: 'daftarbelanja-fb1b4.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-fb1b4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-fb1b4.firebasestorage.app',
    measurementId: 'G-EF4YQ337TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaW8r5z6XqU-VCYCIfL57KQrQNQTAV954',
    appId: '1:198214518669:android:2dc52e4d5381232de59fc4',
    messagingSenderId: '198214518669',
    projectId: 'daftarbelanja-fb1b4',
    databaseURL: 'https://daftarbelanja-fb1b4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-fb1b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5PF_Y_h6wqDjTxirkHyND0PO6JdKNnYY',
    appId: '1:198214518669:ios:61ff53f57686bbf6e59fc4',
    messagingSenderId: '198214518669',
    projectId: 'daftarbelanja-fb1b4',
    databaseURL: 'https://daftarbelanja-fb1b4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-fb1b4.firebasestorage.app',
    iosBundleId: 'com.example.daftarbelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5PF_Y_h6wqDjTxirkHyND0PO6JdKNnYY',
    appId: '1:198214518669:ios:61ff53f57686bbf6e59fc4',
    messagingSenderId: '198214518669',
    projectId: 'daftarbelanja-fb1b4',
    databaseURL: 'https://daftarbelanja-fb1b4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-fb1b4.firebasestorage.app',
    iosBundleId: 'com.example.daftarbelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVlOZnTx0dX8xidMaqk6CHH1Ly6ySRhtQ',
    appId: '1:198214518669:web:7414b86a41e3ae65e59fc4',
    messagingSenderId: '198214518669',
    projectId: 'daftarbelanja-fb1b4',
    authDomain: 'daftarbelanja-fb1b4.firebaseapp.com',
    databaseURL: 'https://daftarbelanja-fb1b4-default-rtdb.firebaseio.com',
    storageBucket: 'daftarbelanja-fb1b4.firebasestorage.app',
    measurementId: 'G-7PNS853H15',
  );
}
