// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbf3aXCv-Q1cJAbkQhJfiS1u_GJLQoKjM',
    appId: '1:408354982781:web:fd98db3ed8231e5e1a9a14',
    messagingSenderId: '408354982781',
    projectId: 'notes-dbd7f',
    authDomain: 'notes-dbd7f.firebaseapp.com',
    databaseURL: 'https://notes-dbd7f-default-rtdb.firebaseio.com',
    storageBucket: 'notes-dbd7f.firebasestorage.app',
    measurementId: 'G-XS8G1J9MBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWqfUy3yzLSpPl6dnrN1DTWNiGCuV6Lvk',
    appId: '1:408354982781:android:05eb2acee90712551a9a14',
    messagingSenderId: '408354982781',
    projectId: 'notes-dbd7f',
    databaseURL: 'https://notes-dbd7f-default-rtdb.firebaseio.com',
    storageBucket: 'notes-dbd7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtze0ewZ9xHinI2VNtF4T4CpDkLGaosuA',
    appId: '1:408354982781:ios:22d39c46ccd7a8fb1a9a14',
    messagingSenderId: '408354982781',
    projectId: 'notes-dbd7f',
    databaseURL: 'https://notes-dbd7f-default-rtdb.firebaseio.com',
    storageBucket: 'notes-dbd7f.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtze0ewZ9xHinI2VNtF4T4CpDkLGaosuA',
    appId: '1:408354982781:ios:22d39c46ccd7a8fb1a9a14',
    messagingSenderId: '408354982781',
    projectId: 'notes-dbd7f',
    databaseURL: 'https://notes-dbd7f-default-rtdb.firebaseio.com',
    storageBucket: 'notes-dbd7f.firebasestorage.app',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbf3aXCv-Q1cJAbkQhJfiS1u_GJLQoKjM',
    appId: '1:408354982781:web:d5a31107a7313d751a9a14',
    messagingSenderId: '408354982781',
    projectId: 'notes-dbd7f',
    authDomain: 'notes-dbd7f.firebaseapp.com',
    databaseURL: 'https://notes-dbd7f-default-rtdb.firebaseio.com',
    storageBucket: 'notes-dbd7f.firebasestorage.app',
    measurementId: 'G-BJ4WPHHVVG',
  );

}