// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtrCnCdGPYuDa1lJM9SUnnmKNRvDhA_Uo',
    appId: '1:755400346792:web:11bc53980bd05cc5bdc69d',
    messagingSenderId: '755400346792',
    projectId: 'mdpgold-b805b',
    authDomain: 'mdpgold-b805b.firebaseapp.com',
    databaseURL: 'https://mdpgold-b805b-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b805b.firebasestorage.app',
    measurementId: 'G-NB68WSYWEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr4VFBcPsMkoJ-iD2bEwWvk5y-c3rcZEI',
    appId: '1:755400346792:android:3da533fdeadd3030bdc69d',
    messagingSenderId: '755400346792',
    projectId: 'mdpgold-b805b',
    databaseURL: 'https://mdpgold-b805b-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b805b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-NQOXSTatHqeCGEmBsYW_xHivVn-0pc',
    appId: '1:755400346792:ios:de8bfe98e0a5914dbdc69d',
    messagingSenderId: '755400346792',
    projectId: 'mdpgold-b805b',
    databaseURL: 'https://mdpgold-b805b-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b805b.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCH-NQOXSTatHqeCGEmBsYW_xHivVn-0pc',
    appId: '1:755400346792:ios:de8bfe98e0a5914dbdc69d',
    messagingSenderId: '755400346792',
    projectId: 'mdpgold-b805b',
    databaseURL: 'https://mdpgold-b805b-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b805b.firebasestorage.app',
    iosBundleId: 'com.example.mdpGold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtrCnCdGPYuDa1lJM9SUnnmKNRvDhA_Uo',
    appId: '1:755400346792:web:8e797fee9c21156abdc69d',
    messagingSenderId: '755400346792',
    projectId: 'mdpgold-b805b',
    authDomain: 'mdpgold-b805b.firebaseapp.com',
    databaseURL: 'https://mdpgold-b805b-default-rtdb.firebaseio.com',
    storageBucket: 'mdpgold-b805b.firebasestorage.app',
    measurementId: 'G-FD3ML4REP9',
  );
}
